# use base python image with python latest
FROM python:2.7

WORKDIR /o4s/

RUN apt-get update
RUN apt-get -y install libpq-dev python-dev
RUN apt-get -y install vim
RUN pip install pyzmq
EXPOSE 5000
EXPOSE 5001
EXPOSE 22
ADD  . o4s/
CMD ["bash", "o4s/docker_start_master.sh"]